fix: fix workflows backend

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,16 +27,16 @@ jobs:
 
       - name: Run Backend Tests
         run: |
-          docker compose -f docker-compose.yml -f docker-compose.override.test.yml up -d --build
+          docker compose -f docker-compose.yml -f docker-compose.override.test.yml up \
+            --build \
+            --abort-on-container-exit \
+            postgres rabbitMQ user_service merchant_service order_service payment_service drone_delivery_service gateway
 
-          docker compose -f docker-compose.yml -f docker-compose.override.test.yml up --abort-on-container-exit
-          
-          exit_code=0
-          for service in user_service merchant_service order_service payment_service drone_delivery_service gateway; do
-            code=$(docker inspect $(docker compose -f docker-compose.yml -f docker-compose.override.test.yml ps -q $service) --format='{{.State.ExitCode}}' 2>/dev/null || echo 1)
-            [ "$code" != "0" ] && exit_code=1
-          done
-          exit $exit_code
+          docker inspect $(docker compose -f docker-compose.yml -f docker-compose.override.test.yml ps -q) --format='{{.Name}} {{.State.ExitCode}}' | grep -v ' 0$'
+          if [ $? -eq 0 ]; then
+            echo "Some services failed!"
+            exit 1
+          fi
 
       - name: Wait for all tests to complete
         run: |
